es_host: localhost
es_port: 9200
name: Error checks
type: frequency
index: filebeat-*
num_events: 3
timeframe:
  minutes: 3
filter:
- query:
    query_string:
      query: "message:*ERROR*"
alert:
- "email"
email:
- "elastalert@example.com"
smtp_host: localhost
smtp_port: 2525
alert_subject: "Error occurred at {0}"
alert_subject_args:
  - "@timestamp"
alert_text: |-
  timestamp: {0}
  message: {1}
alert_text_args:
  - "@timestamp"
  - message
alert_text_type: alert_text_only
realert:
  minutes: 1
aggregation:
  minutes: 2
